research_task:
  description: >
    Search news about {topic}
    The current time is {date}
  expected_output: >
    A list of news articles about {topic} with the title, url and snippet
  agent: researcher

reporting_task:
  description: >
    Review the context you got.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reporting of the news articles.
    Formatted as markdown without '```'
  agent: reporting_analyst

fact_verification_task:  
  description: >  
    Cross-verify the recommended Ayurvedic medicines and remedies using reliable sources.  
    Ensure their authenticity and accuracy by analyzing available data and references.  
  expected_output: >  
    A detailed verification report listing the recommended Ayurvedic medicines, their sources,   
    and whether they are accurate and trustworthy. Include the medicine name, source URL, and verification status.  
  agent: fact_finder  
  
advisory_task:  
  description: >  
    Recommend the best Ayurvedic medicines and remedies for specific health concerns or conditions.  
    Ensure the recommendations are tailored to the needs and backed by evidence or traditional knowledge.  
  expected_output: >  
    A comprehensive advisory report listing the recommended Ayurvedic medicines and remedies,   
    their purposes, usage guidelines, and any relevant notes. Formatted as markdown without '```'.  
  agent: advisory_analyst  